### ISSUE TITLE
Remove unnessessary <tbody> tab

### ISSUE THREAD

**Issue by lam-nguyen** [LongPotato/Gotato#3]
Every row <tr> in the oder table is wrapped by a <tbody> tag. 
Please remove it.

![image](https://cloud.githubusercontent.com/assets/5128297/8621421/bdedc132-2725-11e5-8d91-7c5ee3d7ff39.png)

**Comment by LongPotato** [comment]
Fixed, the problem was created by ```<tbody>``` tag placed inside ruby scope. 
I moved it outside.
